### ISSUE TITLE
Address legislator name collision possibility

### ISSUE THREAD

**Issue by dphiffer** [aclu-national/elections-api#1]
Currently we don't have a good way of differentiating between two different people with the same name who serve in the same state.

**Comment by kateray** [comment]
As of this PR https://github.com/aclu-national/elections-api/pull/2, we are saving all aclu ids in the NPAD source documents. Since we're updating that manually, if a new legislator comes to office with the same name as their predecessor, we'll be able to make the distinction ourselves.

In the indexing process, we depend on the aclu ids to differentiate, not last names at all.
